AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  Generator: "former2"
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          defualt: DB configuration
        Parameters:
          - RDSMasterUserPassword
          - RDSMasterUser
      - Label:
          default: S3 Configuration
        Parameters:
          - AWSAccessKey
          - AWSSecretKey
Parameters:
  RDSMasterUserPassword:
    Description: Master user password for RDS database
    Type: String
    NoEcho: true
    Default: openreplayPostgres
  RDSMasterUser:
    Description: Master user for RDS database
    Type: String
    Default: openreplay
  AWSAccessKey:
    Description: Access Key to access s3
    Type: String
    Default: ""
  AWSSecretKey:
    Description: Secret Key to access s3
    Type: String
    NoEcho: true
    Default: ""

Description: ""
Resources:
  ElasticLoadBalancingV2TargetGroupWorkers:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: "/"
      Port: 80
      Protocol: "HTTP"
      HealthCheckPort: "traffic-port"
      HealthCheckProtocol: "HTTP"
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 2
      TargetType: "ip"
      Matcher: 
        HttpCode: "200"
      HealthyThresholdCount: 5
      VpcId: !Ref EC2VPC
      Name: "ecs-openre-woker"
  ElasticLoadBalancingV2TargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: "/"
      Port: 80
      Protocol: "HTTP"
      HealthCheckPort: "traffic-port"
      HealthCheckProtocol: "HTTP"
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 2
      TargetType: "ip"
      Matcher: 
        HttpCode: "200"
      HealthyThresholdCount: 5
      VpcId: !Ref EC2VPC
      Name: "ecs-openre-frontend"

  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: "openreplay"
      ClusterSettings: 
      - 
        Name: "containerInsights"
        Value: "enabled"
      CapacityProviders: 
      - "FARGATE_SPOT"
      - "FARGATE"

  ECSLogger:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: OpenReplayECSLogs
      RetentionInDays: 7

  ECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions: 
      - 
        Environment: 
        - 
          Name: "name"
          Value: "nginx"
        - 
          Name: !Ref ECSCluster
          Value: "nginx"
        Essential: true
        Image: "nginx"
        LogConfiguration: 
          LogDriver: "awslogs"
          Options: 
            awslogs-group: !Ref ECSLogger
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: "ecs"
        Name: "nginx"
        PortMappings: 
        - 
          ContainerPort: 80
          HostPort: 80
          Protocol: "tcp"
      Family: "nginx"
      # ExecutionRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole"
      ExecutionRoleArn: !GetAtt ECSRole.Arn
      NetworkMode: "awsvpc"
      RequiresCompatibilities: 
      - "FARGATE"
      Cpu: "1024"
      Memory: "2048"

  ECSService:
    Type: "AWS::ECS::Service"
    DependsOn: 
      - ElasticLoadBalancingV2LoadBalancer
      - ECSRole
    Properties:
      ServiceName: "nginx"
      Cluster: !GetAtt ECSCluster.Arn
      LoadBalancers: 
      - 
        TargetGroupArn: !Ref ElasticLoadBalancingV2TargetGroup
        ContainerName: "nginx"
        ContainerPort: 80
      DesiredCount: 1
      LaunchType: "FARGATE"
      PlatformVersion: "LATEST"
      TaskDefinition: !Ref ECSTaskDefinition
      DeploymentConfiguration: 
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker: 
          Enable: false
          Rollback: false
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: "ENABLED"
          SecurityGroups: 
          - !Ref EC2SecurityGroup
          Subnets: 
          - !Ref EC2Subnet2
          - !Ref EC2Subnet
      HealthCheckGracePeriodSeconds: 0
      SchedulingStrategy: "REPLICA"

  WorkerECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions: 
      - 
        Environment: 
        - 
          Name: "S3_BUCKET_ASSETS"
          Value: !Ref S3Bucket2
        - 
          Name: "GROUP_CACHE"
          Value: "cache-all"
        - 
          Name: "AWS_REGION"
          Value: !Sub "${AWS::Region}"
        - 
          Name: "GROUP_DB"
          Value: "db-all"
        - 
          Name: "GROUP_STORAGE"
          Value: "storage-all"
        - 
          Name: "TOKEN_SECRET"
          Value: "whatewer"
        - 
          Name: "S3_BUCKET_WEB"
          Value: !Ref S3Bucket
        - 
          Name: "GROUP_ENDER"
          Value: "ender-all"
        - 
          Name: "MOBILE_IMAGES_BUCKET"
          Value: !Ref S3Bucket5
        - 
          Name: "GROUP_SINK"
          Value: "sink-all"
        - 
          Name: "REDIS_STRING"
          Value: !GetAtt ElastiCacheCluster.RedisEndpoint.Address

        # TODO: change to chalice:8000/alerts/notifications
        - 
          Name: "ALERT_NOTIFICATION_STRING"
          Value: "REPLACEME"
        - 
          Name: "ASSETS_BUCKET"
          Value: "openreplay-sessions-assets"
        - 
          Name: "ASSETS_ORIGIN"
          # Original value: https://assets-staging.asayer.io
          Value: "/staging/s3/buckets/assets_origin"
        - 
          Name: "AWS_ACCESS_KEY_ID"
          Value: !Ref AWSAccessKey
        - 
          Name: "AWS_SECRET_ACCESS_KEY"
          Value: !Ref AWSSecretKey
        - 
          Name: "POSTGRES_STRING"
          Value: !GetAtt RDSDBInstance.Endpoint.Address
        Essential: true
        # TODO: Change the address to public all image
        Image: "nginx"
        MountPoints: 
        - 
          SourceVolume: "string"
          ContainerPath: "/filestorage"
        Name: "nginx"
        PortMappings: 
        - 
          ContainerPort: 80
          HostPort: 80
          Protocol: "tcp"
        LogConfiguration: 
          LogDriver: "awslogs"
          Options: 
            awslogs-group: !Ref ECSLogger
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: "openreplayworker"
      Family: "WorkerECSService"
      ExecutionRoleArn: !GetAtt ECSRole.Arn
      NetworkMode: "awsvpc"
      Volumes: 
      - 
        Name: "string"
        Host: {}
      RequiresCompatibilities: 
      - "FARGATE"
      Cpu: "2048"
      Memory: "4096"

  WorkerECSService:
    Type: "AWS::ECS::Service"
    DependsOn:
      - ElasticLoadBalancingV2LoadBalancer
      - ECSRole
    Properties:
      ServiceName: "altogether"
      Cluster: !GetAtt ECSCluster.Arn
      LoadBalancers: 
      - 
        TargetGroupArn: !Ref ElasticLoadBalancingV2TargetGroup
        ContainerName: "nginx"
        ContainerPort: 80
      DesiredCount: 1
      LaunchType: "FARGATE"
      PlatformVersion: "LATEST"
      TaskDefinition: !Ref WorkerECSTaskDefinition
      DeploymentConfiguration: 
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker: 
          Enable: false
          Rollback: false
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: "ENABLED"
          SecurityGroups: 
          - !Ref EC2SecurityGroup
          Subnets: 
          - !Ref EC2Subnet2
          - !Ref EC2Subnet
      HealthCheckGracePeriodSeconds: 0
      SchedulingStrategy: "REPLICA"

  EC2VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: "default"
      Tags:
        - 
          Key: "Name"
          Value: "OpenReplay"

  EC2Subnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}b"
      CidrBlock: "10.0.1.0/24"
      VpcId: !Ref EC2VPC
      MapPublicIpOnLaunch: false
      Tags: 
      - 
        Key: "Name"
        Value: !Sub "${ECSCluster}/Private"

  EC2Subnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}a"
      CidrBlock: "10.0.0.0/24"
      VpcId: !Ref EC2VPC
      MapPublicIpOnLaunch: false
      Tags: 
      - 
        Key: "Name"
        Value: !Sub "${ECSCluster}/Public"

  EC2RouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref EC2VPC

  EC2RouteTable2:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref EC2VPC

  EC2VPCDHCPOptionsAssociation:
    Type: "AWS::EC2::VPCDHCPOptionsAssociation"
    Properties:
      DhcpOptionsId: "dopt-3f4ca456"
      VpcId: !Ref EC2VPC

  EC2VPCGatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId: !Ref EC2InternetGateway
      VpcId: !Ref EC2VPC

  EC2InternetGateway:
    Type: "AWS::EC2::InternetGateway"

  EC2SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "openreplay sg"
      GroupName: "openreplaysg"
      VpcId: !Ref EC2VPC
      SecurityGroupIngress: 
      - 
        CidrIp: "0.0.0.0/0"
        FromPort: 80
        IpProtocol: "tcp"
        ToPort: 80
      SecurityGroupEgress: 
      - 
        CidrIp: "0.0.0.0/0"
        IpProtocol: "-1"
  EC2SecurityGroupIngress:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      Description: "Security Group rule for internal communication."
      GroupId: !Ref EC2SecurityGroup
      SourceSecurityGroupId: !Ref EC2SecurityGroup
      SourceSecurityGroupOwnerId: !Ref AWS::AccountId
      IpProtocol: "-1"

  ElasticLoadBalancingV2LoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: !Sub "${ECSCluster}-frontend"
      Scheme: "internet-facing"
      Type: "application"
      Subnets: 
      - !Ref EC2Subnet
      - !Ref EC2Subnet2
      SecurityGroups: 
      - !Ref EC2SecurityGroup
      IpAddressType: "ipv4"

  ElasticLoadBalancingV2Listener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      LoadBalancerArn: !Ref ElasticLoadBalancingV2LoadBalancer
      Port: 80
      Protocol: "HTTP"
      DefaultActions: 
      - 
        Order: 1
        TargetGroupArn: !Ref ElasticLoadBalancingV2TargetGroup
        Type: "forward"

  EC2SubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref EC2RouteTable
      SubnetId: !Ref EC2Subnet

  EC2SubnetRouteTableAssociation2:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref EC2RouteTable
      SubnetId: !Ref EC2Subnet2

  EC2Route:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref EC2InternetGateway
      RouteTableId: !Ref EC2RouteTable

  EC2Route2:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref EC2InternetGateway
      RouteTableId: !Ref EC2RouteTable2

  ECSRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      RoleName: "openreplayECSTaskExecutionRole"
      AssumeRolePolicyDocument: "{\"Version\":\"2008-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ecs-tasks.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
      MaxSessionDuration: 3600
      ManagedPolicyArns: 
      - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
      - "arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess"

###############
## Databases
###############
  RDSDBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "Created from the RDS Management Console"
      DBSubnetGroupName: "openreplayRdsSubnetGroup"
      SubnetIds: 
      - !Ref EC2Subnet
      - !Ref EC2Subnet2

  RDSDBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: "openreplay"
      AllocatedStorage: "20"
      DBInstanceClass: "db.t3.micro"
      Engine: "postgres"
      MasterUsername: !Ref RDSMasterUser
      MasterUserPassword: !Ref RDSMasterUserPassword 
      PreferredBackupWindow: "04:55-05:25"
      BackupRetentionPeriod: 7
      AvailabilityZone: !Sub "${AWS::Region}b"
      PreferredMaintenanceWindow: "thu:06:41-thu:07:11"
      MultiAZ: false
      EngineVersion: "13.3"
      AutoMinorVersionUpgrade: true
      LicenseModel: "postgresql-license"
      PubliclyAccessible: false
      StorageType: "gp2"
      Port: "5432"
      StorageEncrypted: true
      CopyTagsToSnapshot: true
      EnableIAMDatabaseAuthentication: false
      DeletionProtection: false
      DBSubnetGroupName: !Ref RDSDBSubnetGroup
      VPCSecurityGroups: 
      - !Ref EC2SecurityGroup
      MaxAllocatedStorage: 1000
      DBParameterGroupName: "default.postgres13"
      OptionGroupName: "default:postgres-13"

  ElastiCacheSubnetGroup:
    Type: "AWS::ElastiCache::SubnetGroup"
    Properties:
      Description: "Created using openreplay cloudformation."
      CacheSubnetGroupName: "openreplayRedisSubnetGroup"
      SubnetIds: 
      - !Ref EC2Subnet
      - !Ref EC2Subnet2

  ElastiCacheCluster:
    Type: "AWS::ElastiCache::CacheCluster"
    Properties:
      CacheNodeType: "cache.t2.micro"
      Engine: "redis"
      EngineVersion: "6.x"
      NumCacheNodes: 1
      PreferredAvailabilityZone: !Sub "${AWS::Region}b"
      PreferredMaintenanceWindow: "sat:05:30-sat:06:30"
      CacheParameterGroupName: "default.redis6.x"
      CacheSubnetGroupName: !Ref ElastiCacheSubnetGroup
      AutoMinorVersionUpgrade: true
      VpcSecurityGroupIds: 
      - !Ref EC2SecurityGroup
      SnapshotRetentionLimit: 1
      SnapshotWindow: "02:00-03:00"
      ClusterName: "openreplay-redis-001"

##############
# S3 bucket
##############
# Because the name should be globally unique, we are generating a random number from the stack id.
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join
      - "-"
      - - "openreplay-mobs"
        - !Select
          - 0
          - !Split
            - "-"
            - !Select
              - 2
              - !Split
                - "/"
                - !Ref "AWS::StackId"
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - 
          ServerSideEncryptionByDefault: 
            SSEAlgorithm: "AES256"
          BucketKeyEnabled: false
      LifecycleConfiguration: 
        Rules: 
        - 
          AbortIncompleteMultipartUpload: 
            DaysAfterInitiation: 7
          Id: "remove30"
          Status: "Enabled"
          ExpirationInDays: 30
      CorsConfiguration: 
        CorsRules: 
        - 
          AllowedHeaders: 
          - "Authorization"
          AllowedMethods: 
          - "GET"
          - "HEAD"
          AllowedOrigins: 
          - "*"

  S3Bucket2:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join
      - "-"
      - - "openreplay-sessions-assets"
        - !Select
          - 0
          - !Split
            - "-"
            - !Select
              - 2
              - !Split
                - "/"
                - !Ref "AWS::StackId"
      LifecycleConfiguration: 
        Rules: 
        - 
          AbortIncompleteMultipartUpload: 
            DaysAfterInitiation: 1
          Id: "remove30"
          Status: "Enabled"
          ExpirationInDays: 30
      CorsConfiguration: 
        CorsRules: 
        - 
          AllowedHeaders: 
          - "*"
          AllowedMethods: 
          - "GET"
          AllowedOrigins: 
          - "*"

  S3Bucket3:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join
      - "-"
      - - "openreplay-static"
        - !Select
          - 0
          - !Split
            - "-"
            - !Select
              - 2
              - !Split
                - "/"
                - !Ref "AWS::StackId"

  S3Bucket4:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join
      - "-"
      - - "openreplay-sourcemaps"
        - !Select
          - 0
          - !Split
            - "-"
            - !Select
              - 2
              - !Split
                - "/"
                - !Ref "AWS::StackId"
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - 
          ServerSideEncryptionByDefault: 
            SSEAlgorithm: "AES256"
          BucketKeyEnabled: false
      CorsConfiguration: 
        CorsRules: 
        - 
          AllowedHeaders: 
          - "Authorization"
          AllowedMethods: 
          - "GET"
          - "HEAD"
          AllowedOrigins: 
          - "*"
  S3Bucket5:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join
      - "-"
      - - "asayer-sessions-mobile-assets"
        - !Select
          - 0
          - !Split
            - "-"
            - !Select
              - 2
              - !Split
                - "/"
                - !Ref "AWS::StackId"
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - 
          ServerSideEncryptionByDefault: 
            SSEAlgorithm: "AES256"
          BucketKeyEnabled: false
